server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lpx?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.demo.bean

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

redis:
      # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
      database: 3
      # redis服务器地址（默认为loaclhost）
      host: 127.0.0.1
      # redis端口（默认为6379）
      port: 6379
      # redis访问密码（默认为空）
      password: 123456
      # redis连接超时时间（单位毫秒）
      timeout: 3000
      # redis连接池配置
      pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

